# Generated by Django 5.0.6 on 2024-11-09 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlshortenermodel',
            name='short_url',
            field=models.TextField(),
        ),
    ]
