# Generated by Django 5.0.6 on 2024-11-09 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_urlshortenermodel_short_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlshortenermodel',
            name='short_url',
            field=models.TextField(unique=True),
        ),
    ]
